name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Deploy to Production Server
        run: |
          echo "🎉 Deploying Spring Boot to PRODUCTION server..."
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Environment,Values=prod" \
            --parameters 'commands=[
              "cd /var/www/your-spring-app",
              "git pull origin main",
              "chmod +x gradlew",
              "./gradlew clean build -x test",
              "sudo systemctl stop your-spring-app || true", 
              "cp build/libs/*.jar /opt/your-spring-app/app.jar",
              "sudo systemctl start your-spring-app"
            ]'
